
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A0B918FA62D65D1B431C63227B3375EA'
    
_lr_action_items = {'AND':([1,3,4,5,7,13,15,16,17,18,],[-6,-8,-9,-10,11,-7,-11,-4,-5,11,]),'PREDICATE':([0,2,8,11,12,14,],[4,4,4,4,4,4,]),'RPAREN':([1,3,4,5,7,10,13,15,16,17,18,],[-6,-8,-9,-10,-3,15,-7,-11,-4,-5,-2,]),'NEGPREDICATE':([0,2,8,11,12,14,],[5,5,5,5,5,5,]),'IMPLY':([1,3,4,5,7,9,10,13,15,16,17,18,],[-6,-8,-9,-10,-3,14,14,-7,-11,-4,-5,-2,]),'LPAREN':([0,2,8,11,12,14,],[2,2,2,2,2,2,]),'NOT':([0,2,11,12,14,],[8,8,8,8,8,]),'OR':([1,3,4,5,7,13,15,16,17,18,],[-6,-8,-9,-10,12,-7,-11,-4,-5,12,]),'$end':([1,3,4,5,6,7,9,13,15,16,17,18,],[-6,-8,-9,-10,0,-3,-1,-7,-11,-4,-5,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,2,11,12,14,],[1,1,16,17,1,]),'factor':([0,2,8,11,12,14,],[3,3,13,3,3,3,]),'expression':([0,2,],[9,10,]),'statement':([0,],[6,]),'sentense':([0,2,14,],[7,7,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statment_expression','homework.py',46),
  ('expression -> expression IMPLY sentense','expression',3,'p_expression_imple','homework.py',51),
  ('expression -> sentense','expression',1,'p_expression_sentense','homework.py',55),
  ('sentense -> sentense AND term','sentense',3,'p_sentense_and','homework.py',59),
  ('sentense -> sentense OR term','sentense',3,'p_sentense_or','homework.py',63),
  ('sentense -> term','sentense',1,'p_sentense_term','homework.py',67),
  ('term -> NOT factor','term',2,'p_term_not','homework.py',71),
  ('term -> factor','term',1,'p_term_factor','homework.py',91),
  ('factor -> PREDICATE','factor',1,'p_factor_predict','homework.py',95),
  ('factor -> NEGPREDICATE','factor',1,'p_factor_negpredict','homework.py',99),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expression','homework.py',103),
]
